// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAZ7vI92kml1U5AcT4NXBsO5Pa6xpoKgQ',
    appId: '1:905609277316:web:c9a4f190bcd373aed7b7d1',
    messagingSenderId: '905609277316',
    projectId: 'bankinfo-8c091',
    authDomain: 'bankinfo-8c091.firebaseapp.com',
    storageBucket: 'bankinfo-8c091.appspot.com',
    measurementId: 'G-GZ9DF07VTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7r-E_9YDVAl5qCKxBVVGZgib1Lvmw5qc',
    appId: '1:905609277316:android:7203489a553c2085d7b7d1',
    messagingSenderId: '905609277316',
    projectId: 'bankinfo-8c091',
    storageBucket: 'bankinfo-8c091.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOKT5CwUrY2xgpD-NQAERCfC2narIE3-A',
    appId: '1:905609277316:ios:2c6bc60a1999bb20d7b7d1',
    messagingSenderId: '905609277316',
    projectId: 'bankinfo-8c091',
    storageBucket: 'bankinfo-8c091.appspot.com',
    iosBundleId: 'com.example.bankInfo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOKT5CwUrY2xgpD-NQAERCfC2narIE3-A',
    appId: '1:905609277316:ios:2c6bc60a1999bb20d7b7d1',
    messagingSenderId: '905609277316',
    projectId: 'bankinfo-8c091',
    storageBucket: 'bankinfo-8c091.appspot.com',
    iosBundleId: 'com.example.bankInfo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAZ7vI92kml1U5AcT4NXBsO5Pa6xpoKgQ',
    appId: '1:905609277316:web:5aa115b4441e510dd7b7d1',
    messagingSenderId: '905609277316',
    projectId: 'bankinfo-8c091',
    authDomain: 'bankinfo-8c091.firebaseapp.com',
    storageBucket: 'bankinfo-8c091.appspot.com',
    measurementId: 'G-LVHGEX27Q7',
  );
}
